name: Build Font

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install FontForge
        run: |
          sudo apt update
          sudo apt install -y fontforge python3-fontforge

      - name: Build font
        run: |
          fontforge -script build_font.py

      - name: Commit generated font
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add MyFont.ttf

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto build font"
            git push
          fi
