name: Build Font

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install FontForge
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fontforge \
            python3-fontforge

      - name: Install VTracer
        run: |
          cargo install vtracer

      - name: Add Cargo to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Build font
        run: |
          fontforge -script build_font.py

      - name: Commit font
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add MyFont.ttf

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Auto build font"
            git push
          fi
